/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class haushaltsbuch_update_mac_SparkleActivator */

#ifndef _Included_haushaltsbuch_update_mac_SparkleActivator
#define _Included_haushaltsbuch_update_mac_SparkleActivator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     haushaltsbuch_update_mac_SparkleActivator
 * Method:    initSparkle
 * Signature: (Ljava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_haushaltsbuch_update_mac_SparkleActivator_initSparkle
  (JNIEnv *, jclass, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
